### ISSUE TITLE
Can not handle exception from cjCall

### ISSUE THREAD

**Issue by sergeypayu** [leaningtech/cheerpj-meta#9] opened 2017-10-23 17:19 UTC
Even if I put cjCall in a try section I still get errors in console and no error reporting.

```
try {
  cjCall(...).then(function(resp) {
   // never called if there is internal java exception
   // function call just disappears forever, there is no way to get this promise resolved if there is an exception
    ...
  });
} catch (err) {
  // also never called
  console.error(err);
}
```

How can I hande errors from CheerpJPromise? Will there be addede something like a 'catch' callback in regular Promise? Also, wiil you consider using regular Promisses instead of custom ones?

Also, how can I turn off cjReportError since it generates XHR error and I obviously don't want to allow cross-domain requests from my domain?

**Comment by alexp-sssup** [comment] 2017-10-23 19:01
There is currently no support for handling exceptions from a CheerpJPromise, although it is planned for the final release of CheerpJ. There is no way at the moment to disable automated error reporting, which is working fine notwithstanding the XHR error.

**Comment by sergeypayu** [comment] 2017-10-24 21:05
Appropriate error handling is a very important and anticipated by me feature. I use cheerpJ to convert a library and exceptions is a standard way to handle error situations. Do you have a roadmap for this feature?

as for XHR, I understand that it works fine even though it can not post error log to your google form. Still, it generates errors in the console and we will need a way to avoid this in production code.

**Comment by alexp-sssup** [comment] 2017-10-24 21:12
Support for handling exceptions will be part of CheerpJ 1.0 release, which will be released before the end of the year. We will provide a way to disable automated error reporting as well in CheerpJ 1.0.

**Comment by sergeypayu** [comment] 2018-05-04 14:29
So the 1.0 release happened in March, but apparently still no exception handling. Any ETA on this feature? we do need it much - we plan to convert jar library that uses exception throwing to report errors in method calls.

**Comment by alexp-sssup** [comment] 2018-05-04 14:57
Due to a large technical backlog, and pressure from several key early adopters to release a 1.0, we had to postpone those two features (among others) to 1.1, which we are going to release very soon.

**Comment by alexp-sssup** [comment] 2018-05-06 21:04
We will consider using standard promises, but it is not a priority for us. We have to understand the consequences in terms of browser compatibility, moreover the construction of standard promises is actually far from convenient.

**Comment by alexp-sssup** [comment] 2018-05-30 13:49
Current ```latest``` supports standard JS promises and exception handling. We have updated the relevant documentation here: https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API#cjcall--cjnew

Is this sufficient for your purposes? We gladly welcome feedback.

**Comment by sergeypayu** [comment] 2018-06-13 12:37
Thank you for the implementation. We are almost there. Last thing you need to fix is ability to chain promises. You current code redefines then and catch functions of the built-in Promise in the way that makes it impossible to chain like this:

```
function initCheerpJ() {
    return cjNew('com.mycoolpackage.MyCoolClass').then(function(result) {
        // do stuff with result
    });
}

// main code
initCheerpJ().then(function(result) {
    // we have successfully initialized cherpj
});
```
Fortunately it is a quick fix. In your loader.js at function cheerpjPromiseAdapter() change the following lines to:
```
ret.then = function(a, b) { if(b) ret.hasCatch = true; **return** Promise.prototype.then.call(this, a, b); };
ret.catch = function(a) { if(a) ret.hasCatch = true; **return** Promise.prototype.catch.call(this, a); };
```

**Comment by sergeypayu** [comment] 2018-06-13 12:48
And one more thing. Exceptions correctly fail Promise but generate Unhanded exception log entry which ignores disableErrorReporting flag.

**Comment by alexp-sssup** [comment] 2018-06-13 15:45
Promise chaining should now be fixed in current ```latest```

The ```Unhanded exception``` message comes from the browser, not from CheerpJ. The ```disableErrorReporting``` flag is only intended to disable automated bug reporting, it has nothing to do with errors shown by the browser.

**Comment by sergeypayu** [comment] 2018-06-14 11:42
I confirm, chaining works now. As for exception, it's not the browser exception. It's loader.js:2011. In the function cheerpjThrow you have console.log. I use cheerpj to call functions from java library and exceptions are a standard way to communicate input error. Consider the following code:

```
function encryptData(data, password) {
    return cjCall(...);
}

// main code
var data = ...;
var password = ...;
encryptData(data, password).then(function() {
    // great success
}).catch(function(err) {
    // report error to user
});
```
If the password is wrong a correct exception will be raised and caught. But there still will be a message generated by your loader.js in the console. On a production env I expect cheerpj to remain silent and comply with the disableErrorReporting flag.

**Comment by alexp-sssup** [comment] 2018-06-14 13:27
This second issue should also be fixed in current ```latest``` as of now.

**Comment by sergeypayu** [comment] 2018-06-14 15:13
Yep, looks nice. Thank you! I guess we can close this ticket now.

**Comment by sergeypayu** [comment] 2018-06-15 13:55
Hello again. Looks like we still have issues with exception handling. I'm calling an erroneous function in my library and loader.js correctly calls cheerpjThrow with the correct detailedMessage, but this error doesn't reject the promise because currentThread.parent is null:
```
if(currentThread.parent && currentThread.parent.endPromise.hasCatch) // < --- parent is indeed null
    currentThread.parent.endPromise.fail(detailMessage);
```
I didn't have enough time to investigate, but It might be related to the fact that the only place you assign thread parent is CheerpJProcess prototype. It has own array of threads. While currentThread is always points to the global threads array. So it appears that you set up parent only for CheerpJProcess.threads and not for the global threads. Hope this helps.

**Comment by alexp-sssup** [comment] 2018-06-15 14:21
That code is only used to handle the final exception from a cheerpjRunMain command (i.e. when a whole process exits with an exception). Other exceptions are handled while looping over the ```continuationStack```. Can you share with us an example so that we can reproduce the issue?

**Comment by sergeypayu** [comment] 2018-06-15 14:37
I can repeat the problem on my library providing an example will require sending the whole library. I probably can create a more lightweight version to demonstrate the problem, but maybe there is something I can give you from the dev console to save time on preparations?

From what I see in debugger cheerpJ creates 2 threads upon initialization when I call cheerpjInit (both of them don't have parent property), then when I call cheerpjRunMain a new thread is created inside cheerpjRunStaticMethod with the parent property, but this thread is immediately closed. After that I see in the debugger that all subsequent calls to cjCall are run on the very first thread that doesn't have parent.

**Comment by alexp-sssup** [comment] 2018-06-15 14:46
The behaviour you are describing is normal, calls done using ```cjCall``` run on the system thread and are not part of a process. Do you have a reject handler attached with ```Promise.catch``` or ```Promise.then```? Does the code in ```cheerpjPromiseResolveE``` (notice the final E) get called? Anyway, it may be just simpler to let us try the code. Signing an NDA (if required) is not a problem.

**Comment by sergeypayu** [comment] 2018-06-15 15:55
Ok, I was able to narrow the problems down. Consider the following code:

```
  var library;
  return cjNew('myCoolLib').then(function(lib) {
    library = lib;
  }).then(function() {
    var data = getCheerpJByteArray(new Uint8Array(2));
    return cjCall(library, 'methodThatThrowsException', data);
  }).catch(function(e) {
    console.error(e);
  });
```
Everything works as expected and `cheerpjPromiseResolveE` is called.

But if I modify it to the following code:
```
  var library;
  return cjNew('myCoolLib').then(function(lib) {
    library = lib;
  }).then(function() {
    var data = getCheerpJByteArray(new Uint8Array(2));
    return cjCall(library, 'methodThatThrowsException', data).then(function(result) {
      console.log(result);
    }).catch(function(e) {
      console.error(e);
    });
  }).catch(function(e) {
    console.error(e);
  });
```
And now no promises are rejected.

**Comment by alexp-sssup** [comment] 2018-06-25 08:52
We have identified the problem, but we did not have the time to fix it yet.

**Comment by sergeypayu** [comment] 2018-06-25 13:28
Thank for the update! Is there an ETA?

**Comment by alexp-sssup** [comment] 2018-06-27 08:41
The problem should be fixed in current ```latest```. Remember to clear your local cache to get the new code.

**Comment by alexp-sssup** [comment] 2018-07-13 13:06
We are now ready to release 1.1, it would be great if you could confirm if exception handling is working for you now.

**Comment by sergeypayu** [comment] 2018-07-17 11:37
Hi, sorry about delay in response! Looks like the latest is working properly and promises in different scopes are chained correctly. Thanks for resolving this issue!

**Closed** 2018-07-17 12:05 UTC
