### ISSUE TITLE
Race condition when using custom cheerpj- prefixed tags

### ISSUE THREAD

**Issue by werthsache** [leaningtech/cheerpj-meta#49] opened 2018-12-04 14:16 UTC
Hello,

I recently converted an applet to an application and let it run successfully in several browsers using cheerpj. Thanks a lot, a very cool invention!!

But somehow I cannot run applets using the same mechanism as described in the doc. The same applet runs with the appletviewer, it runs with the cheerpj-applet-runner, it runs under safari, but not with the cheerpj-applet tags and the loader.js library.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CheerpJ test</title>
    <script src="https://cjrtnc.leaningtech.com/latest/loader.js"></script>
    <script>cheerpjInit();</script>
  </head>
  <body>
  </body>
  <script>cheerpjCreateDisplay(700,400);</script>
  <cheerpj-applet code="Smapplet.class" archive="Smapplet.jar" width=700 height=400>
  </cheerpj-applet>
</html>
```

It drives me crazy, what am I doing wrong? Thank you.

**Comment by alexp-sssup** [comment] 2018-12-04 14:19
The applet tag is outside of the ```<body>```. That is very suspicious. Also, cheerpjCreateDisplay is not required when converting applets.

**Comment by werthsache** [comment] 2018-12-04 14:51
Thank you for the quick answer... I removed the cheerpjCreateDisplay and placed the applet-tag within the body-environment but still the same. I get "Cheerpj Runtime Ready", then "graphics system is initializing", then "loading..." and nothing shows. Here's my litte test program:

```
  import java.awt.*;
  import java.awt.event.ActionEvent;
  import java.awt.event.ActionListener;
  import java.applet.Applet;

public class Smapplet extends Applet implements ActionListener
  {

    Button b;

    public void init ()
    {
        b = new Button ("HUHU");
        this.add(b);
        b.addActionListener(this);
    }

  @Override
  public void actionPerformed(ActionEvent e) {
    System.out.println("Action");
  }
}
```
It shows a button with HUHU and if you press it, it writes action on the console (if present;). Attached also my jar and jar.js in as single zip ... thank you so!

[Archiv.zip](https://github.com/leaningtech/cheerpj-meta/files/2644501/Archiv.zip)

**Comment by alexp-sssup** [comment] 2018-12-04 15:16
The bug is an unexpected side effect of using the custom ```cheerpj-applet``` tag. Since the style for the custom tag is defined in a special css file there is a race condition where the applet tag can be converted too soon, when it's styling it's not yet properly known. Use a plain ```<applet>``` tag. We will add an internal task about this problem and let you know when it's fixed.

**Comment by werthsache** [comment] 2018-12-04 16:16
Ok... this worked and I am a way further, thanks a lot! It now runs under chrome and even firefox. With safari I get a "is not allowed by Access-Control-Allow-Origin" error, but this might be a safari thing.

Most important is: Do use
```
<script src="https://cjrtnc.leaningtech.com/1.2/loader.js"></script>
```
instead of 
```
<script src="https://cjrtnc.leaningtech.com/current/loader.js"></script>
```
as the current version brings an **Uncaught ReferenceError: cheerpjInit is not defined** error for some reason I don't understand!

Thank you for your great support!

**Comment by alexp-sssup** [comment] 2018-12-04 16:21
Please use ```1.3``` instead of ```1.2```. The other error is caused by a type, the endpoint is ```latest``` not ```current```.

**Comment by werthsache** [comment] 2018-12-04 16:25
There is an issue, but by trying to reproduce the error I did a typo. When I use 1.3 I get an **loader.js:397 Uncaught ReferenceError: cheerpjFree is not defined** error which does not occur with 1.2. I apology for the confuse!

**Comment by werthsache** [comment] 2018-12-04 16:34
Yes of course! I have to mention, that I did the conversion with the cheerpj_1.3/cheerpjfy.py version, that I downloaded recently from your page.

[ar.zip](https://github.com/leaningtech/cheerpj-meta/files/2644919/ar.zip)

**Comment by alexp-sssup** [comment] 2018-12-04 16:41
I cannot see any problem with 1.3. I suspect you might have seen a temporary failure at the CDN level since 1.3 is new and not fully cached yet. I recommend to clear you browser caches and try again.

**Comment by werthsache** [comment] 2018-12-04 16:51
Amazing, you are absolutely right! Thanks!

**Comment by alexp-sssup** [comment] 2019-06-19 10:59
This issue is fixed in our master branch, the fix will be included in the upcoming release.

**Closed by alexp-sssup** 2019-06-19 10:59 UTC
