### ISSUE TITLE
Cheerpj crashes when reading files

### ISSUE THREAD

**Issue by ferdinandmehlan** [leaningtech/cheerpj-meta#25] opened 2018-03-20 20:41 UTC
Our cheerpj-translated project seems to crash when trying to read a file. The file exists in the virtual filesystem cheerpj uses.

**Comment by alexp-sssup** [comment] 2018-03-21 09:06
We need more details to understand your issue. Can you provide a reproducible test case? Filesystem code is heavily used both by us and by our customers, so if there is a problem it must be specific to your application or setup.

**Comment by alexp-sssup** [comment] 2018-03-27 12:03
Closing due to lack of information. Please reopen if you can provide a reproducible test case.

**Closed by alexp-sssup** 2018-03-27 12:03 UTC
