### ISSUE TITLE
cheerpj 1.3 crashes on Windows with can't decode bye 0x8f

### ISSUE THREAD

**Issue by vonwenckstern** [leaningtech/cheerpj-meta#50] opened 2018-12-12 02:00 UTC
Hi,

when we try to compile the JAR file of: 

https://rwth-aachen.sciebo.de/s/igDWzLpdO5zYHBj/download?path=%2Fshared%2F18.12.03.ocl-verification&files=oclverification.zip 

we receive the following error message:
![image](https://user-images.githubusercontent.com/30497492/49841901-b60ecb00-fdb9-11e8-80be-dbafaaa7c446.png)

I just want to tell you the error, the previous cheerpj version could compile our tool; cf. #11 

Best,
Michael

**Comment by vonwenckstern** [comment] 2018-12-12 12:07
The Jar file is linked above, it is only packed in a ZIP file. @alexp-sssup the zip file contains only of this JAR file. So just download it and unpack it.

Here is the Link: https://rwth-aachen.sciebo.de/s/igDWzLpdO5zYHBj/download?path=%2Fshared%2F18.12.03.ocl-verification&files=oclverification.zip

**Comment by alexp-sssup** [comment] 2018-12-13 11:09
The same problem existed in 1.2, and it is caused by non-ascii field names in one of the class files. The problem should be fixed now in our master branch, but in general we do not fully support non-ascii names in class file. It may still work though. As a workaround you can build the JAR on Linux for the time being.

**Comment by vonwenckstern** [comment] 2018-12-17 12:43
@alexp-sssup we analyzed it further, and we also receive a problem when compiling classes which have no non-ascii character, e.g., `de/monticore/umlcd4a/cd4analysis/_ast/ASTCDCompilationUnit.class` (cf. Regex search does not match any non-ascii character).

![image](https://user-images.githubusercontent.com/30497492/50087774-5c673000-0201-11e9-9e23-93022353f73b.png)

I will append for you the generated Java class causing the error, and the cheerpJ output zipped:

[ASTCDCompilationUnit.zip](https://github.com/leaningtech/cheerpj-meta/files/2686024/ASTCDCompilationUnit.zip)

**Comment by alexp-sssup** [comment] 2018-12-17 13:14
It is a most probably a completely different issue

**Comment by vonwenckstern** [comment] 2018-12-18 02:17
@alexp-sssup, @ferdinandmehlan
Interesting is that it works for cheerpJ 1.0:
![image](https://user-images.githubusercontent.com/30497492/50127667-67a67400-0272-11e9-8f31-35afa13a27b5.png)

It does not work for cheerpJ 1.1:
![image](https://user-images.githubusercontent.com/30497492/50127863-1d71c280-0273-11e9-9333-21ee8e7de84e.png)


Here is the JAR file I used for testing:
[ocl-1.2.2-cli.zip](https://github.com/leaningtech/cheerpj-meta/files/2688594/ocl-1.2.2-cli.zip)

**Comment by alexp-sssup** [comment] 2018-12-19 16:53
First of all, please do not use older versions of CheerpJ. We cannot provide support for them.

The crash on de/monticore/umlcd4a/cd4analysis/_ast/ASTCDCompilationUnit.class happens because that class is broken. Internally it calls the method ```de.monticore.ast.ASTCNode.deepClone(de.monticore.ast.ASTNode)``` which do not exists. This calls happens from method ```de.monticore.umlcd4a.cd4analysis._ast.ASTCDCompilationUnit.deepClone```

I think you might have incompatible classes inside the JAR.

Older versions of CheerpJ did less checks on the validity of classes and so there was no crash. But the class was broken nonetheless and it would most probably crash at runtime if the broken part was used.

**Comment by vonwenckstern** [comment] 2018-12-19 17:00
Hi  @alexp-sssup,

I do not want to use an older version of cheerpJ, it is just that we did not get our tool to work in a newer version.

And the `ASTCNode` class exists in the JAR:
![image](https://user-images.githubusercontent.com/30497492/50235369-038dc800-03b8-11e9-9c99-fe9d9aca5e1f.png)

**Comment by alexp-sssup** [comment] 2018-12-19 17:05
ASTCNode exists, but the definition of the method is different.

```de.monticore.ast.ASTNode deepClone()```

It takes no parameter. These two classes could not be compiled together which suggests that the binaries from different versions of this library ended up in this JAR by mistake.

**Comment by vonwenckstern** [comment] 2018-12-19 17:06
@alexp-sssup Ok, thank you for your information. I will take a close look and try to understand why it happens.

**Comment by vonwenckstern** [comment] 2018-12-19 17:22
@alexp-sssup I think that the jar is correct, because `ASTNode` and `ASTCNode` both have the two methods `ASTNode deepClone()` and `default public ASTNode deepClone(ASTNode result)`. `ASTCNode` inherits the second one from the default implementation of implementing the interface.

![image](https://user-images.githubusercontent.com/30497492/50236241-35079300-03ba-11e9-9b8b-c2688b24c82d.png)
![image](https://user-images.githubusercontent.com/30497492/50236295-50729e00-03ba-11e9-87e0-15f3a298f48d.png)
![image](https://user-images.githubusercontent.com/30497492/50236440-ac3d2700-03ba-11e9-973e-046fbfc37635.png)

**Comment by alexp-sssup** [comment] 2018-12-20 09:56
@vonwenckstern Yes, you are right. There was a bug in the compile time resolution of ```default``` methods. The bug is now fixed in our latest branch, unfortunately you will need to wait the public release of CheerpJ 1.4 to get a new binary compiler which includes this fix.

**Closed by alexp-sssup** 2018-12-20 09:56 UTC

**Comment by vonwenckstern** [comment] 2018-12-20 10:55
@alexp-sssup this sounds very good. So we are looking forward version 1.4 ;)
