### ISSUE TITLE
Can't use cheerpJ with josm

### ISSUE THREAD

**Issue by Andor233** [leaningtech/cheerpj-meta#94] opened 2020-09-01 02:37 UTC
I'm try use cheerpJ with josm : https://josm.openstreetmap.de/ 
But I got some runtime error and cheerpJ can't start.
```
Uncaught ReferenceError: jsName is not defined
    anonymous https://cjrtnc.leaningtech.com/2.1/loader.js line 115 > Function:3
    runContinuationStack https://cjrtnc.leaningtech.com/2.1/loader.js:387
    cheerpjSchedule https://cjrtnc.leaningtech.com/2.1/loader.js:1110

```

**Comment by carlopi** [comment] 2020-09-03 08:51
We haven't had the chance to look at it (yet).

Would it be possible for you to share the jar file(s) + html page (either attaching them here or on a accessible repository somewhere) so we can reproduce the problem you are having?

**Comment by alexp-sssup** [comment] 2020-09-06 16:43
@Andor233 We really don't have enough information to debug the problem. Please provide us with a fully reproducible test case and it's likely that we will be able to fix the problem soon.

**Comment by Andor233** [comment] 2020-09-07 03:34
I'm sorry for late.
Here is the jar: https://josm.openstreetmap.de/josm-tested.jar
HTML: https://paste.ubuntu.com/p/fczJnDdT6J/
I'm so sorry I was drowning into Zelda's world in the weeknd.

**Comment by alexp-sssup** [comment] 2020-09-08 10:57
The specific crash on ```jsName``` has been fixed with endpoint ```https://cjrtnc.leaningtech.com/20200907/loader.js```.

Josm still cannot start with CheerpJ though, it is a very complex application which tries to spawn several native programs during the startup process and possibly even access the local python installation.

It is not possible for us to dedicate work on such a complex application without a commercial agreement. If you are interested in our porting services please contact sales@leaningtech.com. It is likely possible to execute Josm in CheerpJ, but this will certainly require custom work on either CheerpJ, Josm, or both.

The scope of CheerpJ is to run 100% of Java applications. Since Josm is interacting with native programs from the system it falls outside the scope of the project. Closing this issue.

**Closed by alexp-sssup** 2020-09-08 10:57 UTC

**Comment by Andor233** [comment] 2020-09-08 16:22
I just want a try. Thank you very much
