### ISSUE TITLE
AWT application does not render 

### ISSUE THREAD

**Issue by apolinario** [leaningtech/cheerpj-meta#158] opened 2023-02-16 00:18 UTC
I'm running an adapted version of https://github.com/amidos2006/Mario-AI-Framework that includes the external files inside the jar file and loads from the jar file as opposed to loading from an external file

However I get a `Uncaught (in promise)` error while trying to run it: 
<img width="1019" alt="Screenshot 2023-02-15 at 23 40 35" src="https://user-images.githubusercontent.com/788417/219270324-d0bf3484-2f58-4ec2-ad2d-659df762a4cb.png">

Here's the *.jar file for reproduction: 
[mario.jar.zip](https://github.com/leaningtech/cheerpj-meta/files/10752231/mario.2.jar.zip)

**Comment by alexp-sssup** [comment] 2023-02-16 08:35
The problem is fixed in the following runtime `https://cjrtnc.leaningtech.com/20230216/loader.js`

Please make sure to remove any previously compiled jar.js, since this new runtime is not compatible with the 2.3 AOT compiler. It should not matter, the level of performance of the internal on-the-fly compiler seems to be sufficient for this game.

**Closed by alexp-sssup** 2023-02-16 08:35 UTC
