### ISSUE TITLE
Unidentified ReferenceError

### ISSUE THREAD

**Issue by siauderman** [leaningtech/cheerpj-meta#46] opened 2018-11-06 09:55 UTC
Hi, I got this error, what does it mean? ReferenceError: _n4VYObjectC2E0 is not defined
![screen shot 2018-11-06 at 5 52 07 pm](https://user-images.githubusercontent.com/14951259/48056582-090ac680-e1ed-11e8-857d-1bd31e7c9b3a.png)

**Comment by alexp-sssup** [comment] 2018-11-06 10:30
What loader.js file are you using?

**Comment by alexp-sssup** [comment] 2018-11-07 07:05
Most probably you are using an outdated loader.js. Make sure to be using the loader.js corresponding to the binary version you are using, for example ```https://cjrtnc.leaningtech.com/1.2/loader.js```

**Comment by alexp-sssup** [comment] 2018-11-18 10:37
Closing, the problem is most probably caused by a mismatch in runtime used vs. AOT compiler used

**Closed by alexp-sssup** 2018-11-18 10:37 UTC
