### ISSUE TITLE
Popup menu bugs

### ISSUE THREAD

**Issue by oeway** [leaningtech/cheerpj-meta#101] opened 2020-09-06 18:09 UTC
I noticed this popup menu bug which stops the user from choosing different tools in the toolbar in https://ij.imjoy.io. I tried to reduce the usage of popup menus, but still cannot avoid it. What I observed is that when multiple popup menu is defined in the same toolbar, I can trigger at the correct location but the content of the popup menu is exactly the same.

If you run the [jar file](https://ij.imjoy.io/ij153/ij-1.53d.jar), the popup menu behaves correctly:
<img width="512" alt="Screenshot 2020-09-06 at 19 (1)" src="https://user-images.githubusercontent.com/478667/92331968-8c600200-f07a-11ea-9c70-8f220c21a7d2.png">

However, if you try the js version at  https://ij.imjoy.io, the content is not correct:
<img width="512" alt="Screenshot 2020-09-06 at 19 56 28" src="https://user-images.githubusercontent.com/478667/92332066-4192ba00-f07b-11ea-8dd9-510787ec07d0.png">

This is the source code for the [Toolbar](https://github.com/imjoy-team/ImageJA.JS/blob/master/src/main/java/ij/gui/Toolbar.java).

Another bug I found is in another window, the popup menu shows correctly for the first time, starting from the second time, it appears for a second and closes. To reproduce this:
1. goto https://ij.imjoy.io
2. click "File -> Open Samples -> AuPbSn 40" and you will see a sample image
3. in the sample image, right click once, and you can see the popup menu, if you right click again, it shows and disappear immediately.

The source code for this part is [here](https://github.com/imjoy-team/ImageJA.JS/blob/a6b84647ca2a645621280ec2ec21c0232c0f1926/src/main/java/ij/gui/ImageCanvas.java#L1253-L1271).

<img width="512" alt="Screenshot 2020-09-06 at 20 08 38" src="https://user-images.githubusercontent.com/478667/92332252-c6320800-f07c-11ea-9244-9016b12b1ba1.png">

**Comment by alexp-sssup** [comment] 2020-10-31 13:53
The second issue should be fixed with endpoint: https://cjrtnc.leaningtech.com/20201031/loader.js

We can't reproduce the first issue you mentioned, please try again with this new build. Make sure, as usual, to disable any custom change before testing. If you can still reproduce the problem please provide some more details and re-open this issue.

**Closed by alexp-sssup** 2020-10-31 13:53 UTC

**Comment by oeway** [comment] 2020-10-31 17:05
@alexp-sssup Thanks, I confirm that the second issue has been fixed, however, not the first one.

I just made a clean preview version for reproducing this issue, you can try it here: https://deploy-preview-28--imagej.netlify.app/ If you right click on the toolbar, for example the rectangle tool, you can see it shows a wrong popup menu, but if you go to https://ij.imjoy.io/ (because I replaced PopupMenu to JPopupMenu) you can see the correct one.

<img width="671" alt="Screenshot 2020-10-31 at 18 02 05" src="https://user-images.githubusercontent.com/478667/97785124-71ee6480-1ba3-11eb-8d73-af12bda5f481.png">

<img width="662" alt="Screenshot 2020-10-31 at 18 02 26" src="https://user-images.githubusercontent.com/478667/97785127-761a8200-1ba3-11eb-9f30-3a8d8b574386.png">


The source code for the toolbar with the popupmenu is here: https://github.com/imagej/ImageJA/blob/master/src/main/java/ij/gui/Toolbar.java

**Comment by oeway** [comment] 2020-10-31 22:40
I noticed that the first bug appears when there is more than one popup menu, it not only happens in the toolbar but also in the image canvas, see the gif below:
![context-menu-bug](https://user-images.githubusercontent.com/478667/97791311-63b73d00-1bd1-11eb-82b0-2bb7d8a6c275.gif)

Here we are suppose to get two different menu depending on where we do right click: 1) on the rectangle ROI it should show a short popup menu 2) outside the rectangle ROI we should see a longer popup menu.

As you see above, the 1st right click is in the rectangle ROI and it works, the 2nd right click also works, but it fails to trigger the right roi for the 3rd time, for the 4th time and afterwards, none of the menus can be triggered (the shows in a flash and disappear immediately, just like the bug second bug you fixed).

**Comment by alexp-sssup** [comment] 2020-11-03 08:45
This additional problem should also be fixed with endpoint: https://cjrtnc.leaningtech.com/20201103/loader.js

**Comment by oeway** [comment] 2020-11-03 10:28
hi @alexp-sssup thanks! I confirm the popupmenu is working perfectly!
