### ISSUE TITLE
printStackTrace() throws exception

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-meta#103] opened 2020-09-24 20:07 UTC
I am using the following innocent code:
```
        StringWriter sr = new StringWriter();
        x.printStackTrace(new PrintWriter(sr));
```
When executing the code I get a NullPointerException:
```
java.lang.NullPointerException
    at java.lang.Throwable.getStackTraceDepth(Unknown Source)
    at java.lang.Throwable.getOurStackTrace(Unknown Source)
    at java.lang.Throwable.printStackTrace(Unknown Source)
    at java.lang.Throwable.printStackTrace(Unknown Source)
```
This seems to be related to another ticket. The cause could
be that getStackTraceDepth() is a native method. And it
simply generates a NullPointerException. So it might be 

really related to this here:

**Reflective call of native unexpectedly throws exception #102**
[https://\github.com/leaningtech/cheerpj-meta/issues/102](https://github.com/leaningtech/cheerpj-meta/issues/102)

**Comment by jburse** [comment] 2020-09-24 20:10
But what makes me nagging is the following. It seems the CheerpJ
itself can print stack traces on the JavaScript console:

![Unbenannt](https://user-images.githubusercontent.com/5411487/94194944-b1de6f80-feb2-11ea-9e5b-13f5bcd81716.PNG)

**Comment by alexp-sssup** [comment] 2020-10-26 13:06
I cannot reproduce this bug, but certainly it is not connected to getStackTraceDepth being a native method. Please provide a fully reproducible test case if you want to investigate the problem.

**Comment by jburse** [comment] 2020-10-26 13:13
The test case was:
```
        StringWriter sr = new StringWriter();
        x.printStackTrace(new PrintWriter(sr));
```

**Comment by alexp-sssup** [comment] 2020-10-26 13:22
Please provide a _fully reproducible test case_, not just snippets of code.

**Comment by alexp-sssup** [comment] 2020-11-23 14:28
Fixed in https://cjrtnc.leaningtech.com/20201123/loader.js

**Closed by alexp-sssup** 2020-11-23 14:28 UTC
