### ISSUE TITLE
Error while compiling jar

### ISSUE THREAD

**Issue by alfaquest** [leaningtech/cheerpj-meta#42] opened 2018-08-12 20:58 UTC
jdk1.8.0_181
Windows 7 Ultimate 64 bit
jar created in Eclipse Mars 2

C:\Users\User\workspace\cheerpj_1.1\football>cheerpjfy.py football.jar
Compiling jar  football.jar
compiling com/alfa/zero/footballMain.class ...
Failure compiling com/alfa/zero/footballMain.class
command: C:\Users\User\workspace\cheerpj_1.1\football\bin\cheerpj "" -llv
m -llvm-exceptions -cp C:\Users\User\AppData\Local\Temp\tmpugbz9vjp\rt.jar.dir\
 com/alfa/zero/footballMain.class
Loading class com/alfa/zero/footballMain and dependencies
Unsupported LLVM generation for opcode c4
In function main

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\Users\User\workspace\cheerpj_1.1\football\bin\cheerpj
File: CheerpJCompilerMethod.cpp, Line 611

Expression: !wide

C:\Users\Music\workspace\cheerpj_1.1\alpha\football>

**Comment by alfaquest** [comment] 2018-08-13 09:34
requested file sent to your gmail account. Thanks for swift reply.

**Comment by alexp-sssup** [comment] 2018-08-13 12:43
There was a bug in compiling very large functions. This is now fixed.

We do not provide nightly builds of the binary compiler (cheerpjfy.py) to our non commercial customers, so you will need to wait for CheerpJ 1.2 (our next release) to build the jar.js file.

In the mean time you can still test. Use our "latest" endpoint (```https://cjrtnc.leaningtech.com/latest/loader.js```) and do _not_ create a jar.js file. The system will automatically compile the classes at run-time. This will be slower compared to using the jar.js file, but it will work.

**Comment by alfaquest** [comment] 2018-08-14 16:00
Thank for all your help. Currently I am trying to find a way to make it work from my side with 1.1, to decrease the size of the main class significantly. Really appreciate you sending on the test env endpoint.

**Comment by bhattmayur** [comment] 2018-11-29 02:50
I am facing same error in new version cheerpj 1.2.

Failure compiling error show. please provide me the solution. I have created very big software in java and now i want to convert it to using cheerpj.

**Comment by alexp-sssup** [comment] 2018-11-29 10:13
The previous error is definitely fixed in 1.2, there must be a different error now. Please provide the full error message. If you recall back in August you only sent me 1 class file for analysis, so it might be that there are different issues still.

**Comment by bhattmayur** [comment] 2018-12-01 11:51
compiling Main/CustomeDataSource2.class ...
Failure compiling Main/CustomeDataSource2.class
command: E:\cheerpj\cheerpj\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\rt.jar.dir\:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\antlrall-2.7.6.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\asm-3.2.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\asm-analysis-3.2.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\asm-commons-3.2.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\asm-tree-3.2.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\asm-util-3.2.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\barbecue-1.5-beta1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\barcode4j-2.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-anim.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-awt-util.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-bridge.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-css.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-dom.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-ext.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-gvt.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-parser.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-script.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-svg-dom.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-svggen.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-util.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\batik-xml.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-beanutils-1.8.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-collections-3.1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-digester-1.7.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-javaflow-20060411.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-logging-1.1.1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-logging-adapters-1.1.1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-logging-api-1.1.1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\commons-logging-tests.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\dsn.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\DynamicJasper-3.1.8.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\groovy-all-1.7.5.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\imap.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasperreports-3.7.3.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jcommon-1.0.15.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jdt-compiler-3.1.1.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\mailapi.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\miglayout-swing.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\n2w.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\napkinlaf-alpha001.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\poi-3.5-beta3.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\pop3.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\swing-layout.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\quaqua.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\quaqua-filechooser-only.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\quaqua-test.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\smtp.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\swt.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\xml-apis.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\xml-apis-ext.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\GujaratiLib4.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\icu4j-3.4.4.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-1.9.0-lite.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-acegisecurity-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-hibernate3-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-hibernate4-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-spring2-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-spring3-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-spring31-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-springsecurity2-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-springsecurity3-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-wicket13-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\jasypt-wicket15-1.9.0.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\Layouts.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\cam.jar.dir:C:\Users\Adm\AppData\Local\Temp\tmpp1wbn39_\bridj-0.7.jar.dir Main/CustomeDataSource2.class

**Comment by alexp-sssup** [comment] 2018-12-01 11:56
From this error message there is nothing I can see. I will need access to the class file to debug this. Send the class file to my email.

**Comment by bhattmayur** [comment] 2018-12-01 11:58
Please give me your mail address. I am facing this error on many classes because i have very big project created in java.

**Comment by alexp-sssup** [comment] 2018-12-01 12:03
alexpigna.dev@gmail.com, you wrote me in the past. Most probably the error is the same for all of them.

**Comment by bhattmayur** [comment] 2018-12-01 12:17
Thanks for replay. I mailed the file. please check it.

**Comment by alexp-sssup** [comment] 2018-12-01 14:38
I cannot reproduce the problem. The class builds fine on my machine.

You should try 2 things:

1) Try again with the just released CheerpJ 1.3, you can download it here: https://www.leaningtech.com/cheerpj/download/noncommercial/. Make sure to uninstall (delete the directories) the previous versions of CheerpJ you have installed.
2) Try again on either a Linux or MacOS machine

**Comment by bhattmayur** [comment] 2018-12-01 16:17
I tried on different different computer but error persist as it as. I attached my jar file please try it again at your side from my original jar file. Please change extension of file from .rar. to .jar.    On Saturday, December 1, 2018, 6:38:07 AM PST, Alessandro Pignotti <notifications@github.com> wrote:  
 
 
I cannot reproduce the problem. The class builds fine on my machine.

You should try 2 things:
   
   - Try again with the just released CheerpJ 1.3, you can download it here: https://www.leaningtech.com/cheerpj/download/noncommercial/. Make sure to uninstall (delete the directories) the previous versions of CheerpJ you have installed.
   - Try again on either a Linux or MacOS machine

**Comment by samlalani** [comment] 2019-04-08 17:32
CheerpJ 1.3
JDK 11.0.2
NetBeans 11

I created a small test Java application with a JFrame that allows the user to enter two numbers and then click "Add" or "Multiply" to get the answer.  However, I am seeing the following output when running cheerpjfy.py on my jar file:

	Compiling jar  TestMath.jar
	compiling testmath/Main.class ...
	compiling testmath/TestFrame.class ...
	Failure compiling testmath/TestFrame.class
	command: C:\Sam\cheerpj_1.3\bin\cheerpj "" -llvm -llvm-exceptions -cp C:\Users\samla\AppData\Local\Temp\tmpqm3a1k3z\rt.jar.dir\ testmath/TestFrame.class
	Loading class testmath/TestFrame and dependencies
	Could not open class java/lang/invoke/StringConcatFactory
	Unsupported LLVM generation for opcode ba
	In function main
	Unsupported LLVM generation for opcode ba
	In function c
	SUPPORT CONSTANT 8Assertion failed!
	
	Program: C:\Sam\cheerpj_1.3\bin\cheerpj
	File: CheerpJCompilerMethod.cpp, Line 2241
	
	Expression: false

The relevant snippet of code is:

            int answer = x + y;
            answer_TextField.setText ("" + answer);
            //answer_TextField.setText ("Sum");

That code gives me the error, but if I comment out the 2nd line and uncomment the third line then it works fine.  Please let me know how to fix it.  Thanks.

**Closed** 2019-04-08 17:57 UTC

**Comment by ComFreek** [comment] 2020-10-12 13:31
@samlalani continued this issue in #65. (for other people coming from Google)

**Comment by pfreon** [comment] 2022-08-06 15:59
Hi there,
I also face the same issue as above-mentioned with CheerpJ, although I used JDK version 8:
compiling fr/ird/climprod/AppelNavigateur.class ...
Failure compiling fr/ird/climprod/AppelNavigateur.class
command: /usr/local/cheerpj_2.3/bin/cheerpj -llvm -llvm-exceptions -cp /tmp/tmp47k1_xta/rt.jar.dir/ fr/ird/climprod/AppelNavigateur.class
Loading class fr/ird/climprod/AppelNavigateur and dependencies
Could not open class java/lang/invoke/StringConcatFactory
Unsupported LLVM generation for opcode ba
In function displayURL
cheerpj: CheerpJCompilerMethod.cpp:2349: uint32_t CheerpJCompiler::compileOpcode(std::ostream&, const ClassFile*, CheerpJCompiler::BasicBlock&, uint32_t, uint32_t, bool, const std::set<int>&, uint16_t, bool): Assertion `false' failed.

The function displayURL within class fr/ird/climprod/AppelNavigateur is as follows:
 static public void displayURL(String url)
 {
    boolean windows = isWindowsPlatform();
    String cmd = null;
    try
    {
      if (windows)
      {
       // cmd = 'rundll32 url.dll,FileProtocolHandler http://...'
        cmd = WIN_PATH + " " + WIN_FLAG + " " + url;
        System.out.println("cmd Windows = " + cmd);
        Process p = Runtime.getRuntime().exec(cmd);
      }
      else
      {
          if (isMacPlatform()){
                cmd = "open " + url;
                System.out.println("cmdmacOS = " + cmd);
                Process p = Runtime.getRuntime().exec(cmd);
          }
          else{
       // Under Unix, Netscape has to be running for the                          "-remote"
              // command to work. So, we try sending the command and
              //check for an exit value. If the exit command is 0,
              // it worked, otherwise we need to start the browser.
              // cmd = 'netscape -remote openURL(http://www.javaworld.com)'
              cmd = UNIX_PATH + " " + UNIX_FLAG +  "(" + "file://" + url + ")"; 
              System.out.println("cmd Linux exitCode 0 Browser open = " + cmd);
              Process p = Runtime.getRuntime().exec(cmd);
              try {
         // wait for exit code -- if it's 0, command  worked,
                  // otherwise we need to start the browser up.
                  int exitCode = p.waitFor();
                  System.out.println("exitCode " + exitCode);
                  if (exitCode != 0) {
               // Command failed, start up the browser
                      // cmd = 'netscape http://www.javaworld.com'
                      cmd = UNIX_PATH  + " " + "(" + "file://" + url + ")"; 
                      System.out.println("cmd Linux exitCode different from 0, Browser closed = " + cmd);
                      p = Runtime.getRuntime().exec(cmd);
                  }
              } catch (InterruptedException x) {
                  System.err.println("Error bringing up browser,cmd='" + cmd + "'");
                  System.err.println("Caught: " + x);
              }
          }
      }
    }
    catch(IOException x)
    {
      // couldn't exec browser
        System.err.println("Could not invoke browser, command=" + cmd);
        System.err.println("Caught: " + x);
    }
}
Please help...
