### ISSUE TITLE
Example program will not work

### ISSUE THREAD

**Issue by nathanchronister** [leaningtech/cheerpj-meta#30] opened 2018-04-19 02:27 UTC
The example program will not progress beyond the spinner. I tried it in MS Edge browser and also Android Chrome browser. I successfully converted the .jar file to .js and copied it into the root directory of my web server along with the example HTML, so I don't know why it doesn't work.

**Comment by alexp-sssup** [comment] 2018-04-19 08:25
We need some more information to understand the problem. What example program are you referring to? What is the output on the browser console.

**Comment by stinkfoot70** [comment] 2018-05-07 15:40
Hi. I'm having the same issue. My jar converted to .js without issue. The following is the guts of test.html

<!DOCTYPE html> 
<html lang="en">   
<head>     
<meta charset="utf-8">     
<title>CheerpJ test</title> 
    
<script src="https://cjrtnc.leaningtech.com/1.0/loader.js"></script>   

</head>   

<body>   

</body>   
<script>       
cheerpjInit();       
cheerpjCreateDisplay(800,600);       
cheerpjRunJar("/app/pong.jar");    
</script> 
</html>

test.html is is a folder on my desktop. pong.jar.js is also in that folder.

In terminal (I'm on a mac), I typed the following:
cd /Users/csaines/Desktop/testpage
python3 -m http.server 8080

which according to the terminal results, seemed to work. 

Then I opened Firefox and went here:
http://127.0.0.1:8080/test.html

I get a browser window with Cheerpj runtime ready with the spinning Cheerpj icon, but it never resolves to my coded program. 

Here's some terminal output if that helps:
127.0.0.1 - - [07/May/2018 09:25:45] "GET /test.htm HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:25:46] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:25:46] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 09:25:46] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:25:46] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 09:25:56] "GET /test.html HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:26:01] "HEAD /pong.jar.js HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:26:01] "GET /pong.jar.js HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:27:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:28:39] "GET /test.html HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:28:40] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:28:40] "HEAD /pong.jar HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 09:28:41] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:28:41] "GET /pong.jar HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 09:37:39] "GET /test.html HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 09:37:42] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:37:42] "HEAD /pong.jar HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 09:37:42] code 404, message File not found
127.0.0.1 - - [07/May/2018 09:37:42] "GET /pong.jar HTTP/1.1" 404 -

Do I have path issues somewhere that I get File not found errors?

Thanks, 
core

**Comment by stinkfoot70** [comment] 2018-05-07 15:41
Sorry. I miscopied the guts of test.html. Here it is in full:

<!DOCTYPE html> 
<html lang="en">   
<head>     
<meta charset="utf-8">     
<title>CheerpJ test</title> 
    
<script src="https://cjrtnc.leaningtech.com/1.0/loader.js"></script>   

</head>   

<body>   

</body>   
<script>       
cheerpjInit();       
cheerpjCreateDisplay(800,600);       
cheerpjRunJar("/app/pong.jar");    
</script> 
</html>

**Comment by stinkfoot70** [comment] 2018-05-07 15:42
I just tried it in Chrome. same result

**Comment by alexp-sssup** [comment] 2018-05-07 15:48
The terminal output you posted is quite confusing. It seems that the same files are sometimes found and sometimes not. Can you clarify if you can access any other, non CheerpJ based, HTML file with your setup?

Moreover the HTML is not really well defined, as it does not have a <html> tag, a <body> and so on. Please use the template from our getting started to being with:

https://github.com/leaningtech/cheerpj-meta/wiki/Getting-started#basic-html-page-for-testing

**Comment by stinkfoot70** [comment] 2018-05-07 16:01
Thanks. Your link is different than the cheerpj tutorial I was using. Especially different is this line:

      cheerpjRunMain("AppClass", "/app/my_application_archive.jar:/app/my_dependency_archive.jar"); 

I'm assuming that my_application_archive.jar will be the jar I built (pong.jar)

What is my_dependency_archive.jar? Is that my pong.jar as well, or is that something different?

**Comment by alexp-sssup** [comment] 2018-05-07 16:03
```my_dependency_archive.jar``` represent the dependency JAR that an application might have in general. You application does not need one apparently.

**Comment by stinkfoot70** [comment] 2018-05-07 16:17
I ran 2 tests:
1) I truncated the RunMain line that we were talking about to this:

cheerpjRunMain("AppClass", "/app/my_application_archive.jar");    

no improvement.

2) I made a non-cheerpj page named general_test.html. I placed it in the same folder as my other html and .js files. Here is the guts of it:

<!DOCTYPE html> 
<html lang="en">   
<head>     
<meta charset="utf-8">     
<title>CheerpJ test</title>     

<script src="https://cjrtnc.leaningtech.com/latest/loader.js"></script>   

</head>   

<body>   
</body>   

<script>       
cheerpjInit();       
cheerpjCreateDisplay(800,600);       
cheerpjRunMain("AppClass", "/app/my_application_archive.jar");    

</script> </html>


I loaded the page in firefox the same way (http://127.0.0.1:8080/general_test.html, as opposed to double clicking on the html file) and the page loaded fine.

**Comment by alexp-sssup** [comment] 2018-05-07 16:40
```cheerpjRunMain("AppClass", "/app/my_application_archive.jar")```

This line is an example, and should not be used as it is. Before your jar was called ```pong.jar``` so it does not make sense to use ```my_application_archive.jar```. The same applies for the main class.

Please upload the HTML page you are using, and the JAR and JAR.JS if possible.

**Comment by alexp-sssup** [comment] 2018-05-07 16:40
Also, see here for common errors: https://github.com/leaningtech/cheerpj-meta/wiki/Frequently-Asked-Questions#my-application-compiled-with-cheerpj-does-not-work-and-i-just-see-the-cheerpj-runtime-ready-on-the-top-of-the-screen-whats-going-on

**Comment by stinkfoot70** [comment] 2018-05-07 16:44
the drag and drop feature of attaching files on this forum didn't accept .js and .html file types, so I packaged them in zip, for the forum to accept the upload. 

[Archive.zip](https://github.com/leaningtech/cheerpj-meta/files/1980682/Archive.zip)

**Comment by alexp-sssup** [comment] 2018-05-07 16:47
You are using ```AppClass``` as the name of the main class for your JAR. That class does not exist. Use the actual name of the main class. If the JAR can normally be run using ```java -jar pong.jar``` you can simply use ```cheerpjRunJar("/app/pong.jar")```

**Comment by alexp-sssup** [comment] 2018-05-07 16:56
Can you upload the JAR?

**Comment by stinkfoot70** [comment] 2018-05-07 16:58
Jar is also not supported to upload on this forum, so I wrapped it in a zip again.

[pong.jar.zip](https://github.com/leaningtech/cheerpj-meta/files/1980730/pong.jar.zip)

**Comment by alexp-sssup** [comment] 2018-05-07 17:04
Ok, on my system the JAR fails after loading with an NullPointerException. I think this JAR is trying to use some ImageIO APIs which are not currently supported. If you just want to try CheerpJ and the actual application does not matter I recommend to follow the tutorial. https://github.com/leaningtech/cheerpj-meta/wiki/Tutorial

**Comment by stinkfoot70** [comment] 2018-05-07 17:09
Interesting. I didn't realize that cheerpj had short-comings like that. Is there another java to javascipt/html5 converter that you recommend? 

This still might work for one use of this that I have in mind. I have student text programs that we've played through terminal, but I'd like them to be able to share them with their friends. I suppose that dropping their text programs into a frame, converting them to .js, and posting to a webpage would be no problem for Cheerpj?

**Comment by alexp-sssup** [comment] 2018-05-07 17:12
CheerpJ is the most advanced converter on the market, and the only one that works on real world large scale application. We have several commercial users that employs CheerpJ in production. This specific application has problems, but it is in no way representative of the capabilities of the program.

You might be also interested in our experimental CheerpJ powered JavaFiddle: https://javafiddle.leaningtech.com/

**Comment by alexp-sssup** [comment] 2018-05-07 17:25
Some part of ImageIO is known to work, I don't know exactly what functionality is causing this failure. If you can identify a smaller program (a test case) that shows the problem is will be easier for us to debug and fix it.

JavaFiddle has exactly the same limitation as CheerpJ, since it uses CheerpJ under the hood.

**Comment by stinkfoot70** [comment] 2018-05-07 17:28
Gotcha. I may play around with cleaning up my pong test program, but most likely I'll try the text program application to this. 

Thanks again for clarifying everything.

**Comment by stinkfoot70** [comment] 2018-05-07 17:29
What is the benefit of your newer JavaFiddle over the regular cheerpj?

**Comment by alexp-sssup** [comment] 2018-05-07 17:32
JavaFiddle is not an alternative to CheerpJ, it's just an online version of the tool to try the technology.

**Comment by stinkfoot70** [comment] 2018-05-07 17:34
Cool. I'm good then. Thanks.

**Comment by alexp-sssup** [comment] 2018-07-26 17:07
Fixed with current "latest"

**Closed by alexp-sssup** 2018-07-26 17:07 UTC

**Comment by jog39** [comment] 2019-02-06 14:04
Hello, the tutorial example doesn't work for me either: the jar is converted to js successfully, then when launching the server it doesn't progress after `main is starting`.
Console output is:
` http-server -p 8080
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://172.18.20.1:8080
Hit CTRL-C to stop the server
[Wed Feb 06 2019 14:49:02 GMT+0100 (CET)] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like G
ecko) Chrome/71.0.3578.98 Safari/537.36"                                                                                           
[Wed Feb 06 2019 14:49:03 GMT+0100 (CET)] "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KH
TML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"                                                                                
[Wed Feb 06 2019 14:49:03 GMT+0100 (CET)] "GET /favicon.ico" Error (404): "Not found"
[Wed Feb 06 2019 14:49:04 GMT+0100 (CET)] "GET /cheerpj.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (K
HTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"                                                                               
[Wed Feb 06 2019 14:49:20 GMT+0100 (CET)] "HEAD /TextDemo.jar" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (
KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"                                                                              
[Wed Feb 06 2019 14:49:20 GMT+0100 (CET)] "GET /TextDemo.jar" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (K
HTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"                                                                               
[Wed Feb 06 2019 14:49:21 GMT+0100 (CET)] "GET /TextDemo.jar.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36
 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`

**Comment by alexp-sssup** [comment] 2019-02-06 14:13
@jog39 There is nothing wrong in the server log. 3 things

1. Is there any error message on the browser console (in the developer tools)
2. What is the code of the ```cheerpj.html``` file you are using.
3. Over slow networks it may take around 30sec-1min for the application to start the first time.

**Comment by jog39** [comment] 2019-02-06 14:28
Console log is 

```loader.js:2576 CheerpJ is initializing
loader.js:438 Uncaught (in promise) 
(anonymous) @ loader.js:438
setTimeout (async)
cheerpjPromiseResolveE @ loader.js:438
cheerpjThrow @ loader.js:2048
cjThrowNPE @ rt.jar.js:516
runContinuationStack @ loader.js:378
cheerpjSchedule @ loader.js:1028
```

Code in `cheerpj.html`is

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CheerpJ test</title>
    <script src="https://cjrtnc.leaningtech.com/1.1/loader.js"></script>
  </head>
  <body>
  </body>
  <script>
      cheerpjInit();
      cheerpjCreateDisplay(800,600);
      cheerpjRunJar("/app/TextDemo.jar");
  </script>
</html>
```
It has been loading for a lot more than 1 min and the network speed is pretty good.

**Comment by alexp-sssup** [comment] 2019-02-06 14:32
Which version of the CheerpJ compiler are you using? If you are using the latest version (1.3), which we recommend then you also need to use the corresponding version of the the loader:

```
https://cjrtnc.leaningtech.com/1.3/loader.js
```

**Comment by jog39** [comment] 2019-02-06 14:34
Oops, I didn't pay attention to that, my bad. It works now thanks!

**Comment by ljcool2006** [comment] 2022-10-24 03:42
Still having this issue, I am using the latest version of the loader
